
/**************************************************************
 *	
 *	bubblyclouds, 8 bit, 11025Hz,
 *	1 channel, 1212192 bytes/channel
 *	Total Size: 1 * 1212192 + 4 (header) = 1212236 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/bubblyclouds.wav
 *	Time-stamp: Sun Dec 04 19:31:53 2016
 *	
 **************************************************************/

#ifndef __BUBBLYCLOUDSH__
#define __BUBBLYCLOUDSH__

#define BUBBLYCLOUDSFREQ 11025
#define BUBBLYCLOUDSLEN 1212192

extern const unsigned char bubblyclouds[1212192];

#endif /* __BUBBLYCLOUDSH__ */
