
/**************************************************************
 *	
 *	gameover, 8 bit, 11025Hz,
 *	1 channel, 44416 bytes/channel
 *	Total Size: 1 * 44416 + 4 (header) = 44460 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/gameover.wav
 *	Time-stamp: Tue Dec 13 19:42:20 2016
 *	
 **************************************************************/

#ifndef __GAMEOVERH__
#define __GAMEOVERH__

#define GAMEOVERFREQ 11025
#define GAMEOVERLEN 44416

extern const unsigned char gameover[44416];

#endif /* __GAMEOVERH__ */
