
/**************************************************************
 *	
 *	hit, 8 bit, 11025Hz,
 *	1 channel, 11232 bytes/channel
 *	Total Size: 1 * 11232 + 4 (header) = 11276 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/hit.wav
 *	Time-stamp: Sun Dec 04 19:49:45 2016
 *	
 **************************************************************/

#ifndef __HITH__
#define __HITH__

#define HITFREQ 11025
#define HITLEN 11232

extern const unsigned char hit[11232];

#endif /* __HITH__ */
