
/**************************************************************
 *	
 *	jump, 8 bit, 11025Hz,
 *	1 channel, 2857 bytes/channel
 *	Total Size: 1 * 2857 + 4 (header) = 2901 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/jump.wav
 *	Time-stamp: Sun Dec 04 19:43:10 2016
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 2857

extern const unsigned char jump[2857];

#endif /* __JUMPH__ */
