
/**************************************************************
 *	
 *	lifelost, 8 bit, 44100Hz,
 *	1 channel, 52224 bytes/channel
 *	Total Size: 1 * 52224 + 4 (header) = 52268 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/lifelost.wav
 *	Time-stamp: Mon Dec 12 16:57:47 2016
 *	
 **************************************************************/

#ifndef __LIFELOSTH__
#define __LIFELOSTH__

#define LIFELOSTFREQ 44100
#define LIFELOSTLEN 52224

extern const unsigned char lifelost[52224];

#endif /* __LIFELOSTH__ */
