
/**************************************************************
 *	
 *	opening, 8 bit, 11025Hz,
 *	1 channel, 2012812 bytes/channel
 *	Total Size: 1 * 2012812 + 4 (header) = 2012856 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/opening.wav
 *	Time-stamp: Sun Dec 04 17:57:13 2016
 *	
 **************************************************************/

#ifndef __OPENINGH__
#define __OPENINGH__

#define OPENINGFREQ 11025
#define OPENINGLEN 2012812

extern const unsigned char opening[2012812];

#endif /* __OPENINGH__ */
