
/**************************************************************
 *	
 *	story_mode, 8 bit, 48000Hz,
 *	1 channel, 8763264 bytes/channel
 *	Total Size: 1 * 8763264 + 4 (header) = 8763308 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/story-mode.wav
 *	Time-stamp: Sun Dec 04 16:43:27 2016
 *	
 **************************************************************/

#ifndef __STORY_MODEH__
#define __STORY_MODEH__

#define STORY_MODEFREQ 48000
#define STORY_MODELEN 8763264

extern const unsigned char story_mode[8763264];

#endif /* __STORY_MODEH__ */
