
/**************************************************************
 *	
 *	winner, 8 bit, 11025Hz,
 *	1 channel, 42240 bytes/channel
 *	Total Size: 1 * 42240 + 4 (header) = 42284 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/michellechiu/Desktop/CS2261/Chiu_Michelle_final_prj/sounds/winner.wav
 *	Time-stamp: Tue Dec 13 19:41:25 2016
 *	
 **************************************************************/

#ifndef __WINNERH__
#define __WINNERH__

#define WINNERFREQ 11025
#define WINNERLEN 42240

extern const unsigned char winner[42240];

#endif /* __WINNERH__ */
